- name: PLAY1
  hosts: local # Ansible is not only used for connecting worker node but it can also connect to its own node or IP
  connection: local # This means anisble can connect to itself without any username and password ; managing its own node, no need of credentials
  tasks: 
  - name: PLAY1 and TASK1
    ansible.builtin.debug:  
      msg: "Hello from PLAY1 and TASK1"

- name: PLAY2
  hosts: local 
  connection: local 
  tasks: 
  - name: PLAY2 and TASK1
    ansible.builtin.debug:  
      msg: "Hello from PLAY2 and TASK1"