- name: PLAY1
  hosts: local # Ansible is not only used for connecting worker node but it can also connect to its own node or IP
  connection: local # This means anisble can connect to itself without any username and password ; managing its own node, no need of credentials
  tasks: 
  - name: PLAY1 and TASK1
    ansible.builtin.debug:  
      msg: "Hello from PLAY1 and TASK1"

- name: PLAY2 # Here i did not understand which server IP it is taking as we only have 1 ansible server and its IP we have mentioned in local
  hosts: local # Now which local it is trying to connect, if its same server then why are we writing 2 playbooks here??
  connection: local 
  tasks: 
  - name: PLAY2 and TASK1
    ansible.builtin.debug:  
      msg: "Hello from PLAY2 and TASK1"