- name: variables from common vars files
hosts: local
connection: local
vars_files:
- course-vars-as-common.yaml
tasks:
- name: print course information
  ansible.builtin.debug:
    msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }}, Trainer name is {{ TRAINER }}"