- name: variables undeclared # WE are not creating any vars neither in this file nor anywhere else
  hosts: local # In inventory.ini file --- COURSE related info is not present-- thstw hy we got error in output
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }}, Trainer name is {{ TRAINER }}"

