- name: Install packages using loops concept
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}" # first time we gave "" against name variable  
      state: installed #/Or we can also give present
    loop:
    - gcc
    - mysql
    - git
    - zip
      