- name: Install few packages and Remove few packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: # The below way of writing is called as list way
    - {name: 'gcc', state: 'present'} 
    - {name: 'mysql', state: 'absent'}
    - {name: 'git', state: 'present'}
    - {name: 'zip', state: 'absent'}