- name: undefined variable testing i.e. filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Anish') }}"

  - name: convert string to list
    vars:
      fruits: "Banana, Apple, Guava" # String to be converted into list
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course: # Map/Dictionary
        name: Devops with AWS
        duration: 120 Hrs
        trainer: Sivakumar 
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"