- name: undefined variable testing i.e. filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Anish') }}"

  - name: convert string to list
    vars:
      fruits: "Banana, Apple, Guava" # String to be converted into list
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course: # Map/Dictionary
        name: Devops with AWS
        duration: 120 Hrs
        trainer: Sivakumar 
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}" # o/p-> will be shown in key value pair 

  - name: convert list into map # ------------- This code is not working for me **************started working
    vars: # List way of writing the variables
      course: 
      - {'key': 'name', 'value': 'devopswithaws'} # I wrote key word in caps i.e., Key for error which i was getting 
      - {'key': 'duration', 'value': '120hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}" # o/p-> will be shown in map format 

  - name: convert upper to lower
    vars:
      name: "Shalini Chintala"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"    
  
  - name: convert lower to upper
    vars:
      name: "shalini chintala"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"  

  - name: print min and max values
    vars:
      numbers: [1,30,57,87,98,46845]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"    

  - name: check IP address is valid or not # This code did not run directly we had to install netaddr python library before running this cmd
    vars:
      ip: "2567:255:25:256"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}" # o/p-> false

  - name: check IP address is valid or not # This code did not run directly we had to install netaddr python library before running this cmd
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}" # o/p-> true