- name: shell vs command module verification
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt # simple command -- > o/p-> some error came so changing this module to shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    # This redirecting commands work only in shell 