- name: shell vs command module verification
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt # simple command -- > o/p-> some error came (becoz of redirecting > command) so changing this module to shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    # This redirecting commands work only in shell environment if its not there then it wont work
  
  - name: execute just ls command without redirecting to any output file i.e., > symbol 
    ansible.builtin.command: ls -ltr # But i want to store the output of this command in a variable for this i am declaring a variable by name command_result and referring as register
    register: command_result

  - name: print the output
    ansible.builtin.command:
      msg: "{{ command_result }}"    