- name: nginx installation
  hosts: all
  become: yes
  serial: 7
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start the nginx
    tags: # dont know the purpose of this
    - run
    ansible.builtin.service:
      name: nginx
      state: started     